### ISSUE TITLE
Unclear error reporting on config.

### ISSUE THREAD

**Issue by janwirth** [carrot/roots-wordpress#8]
I got an <code>object:[object]</code> or something error when pasting an entire URL with http: and closing slash.

**Comment by jescalan** [comment]
Could you provide a tiny bit more information on how you were able to produce the error?

**Comment by janwirth** [comment]
Excuse me, of course.
in <code>app.coffee</code> below 

<pre><code>extensions:
    wordpress:</code></pre>

if you insert a url including the protocol: <pre><code>site: 'http://mywordpress.com'</code></pre>

**Comment by jescalan** [comment]
Try not including the protocol? :grinning:

**Comment by jescalan** [comment]
Also what is the site you are using? I need to be able to reproduce this error in order to fix it

**Comment by sondoha** [comment]
Hi Jenius,

Thank you for your amazing roots-wordpress :)

I'm following your video to connect wordpress and roots. Here is my config:

```
extensions: [
    js_pipeline(files: 'assets/js/*.coffee'),
    css_pipeline(files: 'assets/css/*.styl'),
    wordpress
      site: 'aphblog.dev.sondoha.com'
      post_types:
        post: { template: 'views/_single_post.jade' }
  ]
```

When I run `roots compile` it returns this message: `compiling... [Error: Uncaught, unspecified "error" event.]`

Also, I got this message:

```
compiling... [Error: [object Object]]

Potentially unhandled rejection [4] [object Object] (WARNING: non-Error used)
```

When I run `roots watch`. Do you have any advice?

Thanks,
Son

**Comment by sondoha** [comment]
Hi,

Nevermind :D I have figured it out. I have to disconnect/reconnect the jetpack plugin.

**Comment by randychampagne** [comment]
Hello Jenius,

I am having this same issue using a LAMP box on RedHat Cloud. Please see the roots-wordpress config below. my site compiles but it doesn't fetch any data from the WP backend. the `worpress.post` object is undefined. 

```
wordpress
      site: 'php-randytest2016.rhcloud.com'
      post_types:
        post: { template: 'views/single.jade' }
```

I am running WP v4.5
node v5.4.1
roots v4.0.1

I did as Sondoha suggested and de-activated/re-activated the jetpack plugin several times but the problem persists.

This may not be the appropriate thread for reporting this since it is closed but any guidance will be greatly appreciated.

Cheers!

**Comment by jescalan** [comment]
Hey @champagne-randy -- as you mentioned, wrong place to report the issue.

I'm also to sure I'll be able to debug this, since it's working locally for me. Does it work locally for you but not on the redhead box?

**Comment by randychampagne** [comment]
Thanks for indulging me @jenius. It turns out, `roots-wordpress` did fetch the data. I simply was unable to output it with the jade code from the tutorial. This may stem from some config issue in my system. Below is the workaround I am using. Will investigate further and create a new ticket if issue persists.

```
ul
    for(var post in posts)
        li= post.title
```

Cheers
